# libraries

import os
from snakemake.utils import min_version

min_version("6.4.1")

wildcard_constraints:
    sample="[\da-zA-Z]+",
    replicates="[\d]+"

##### setup report #####
configfile: "config/config.yaml"

##### setup singularity #####


# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
container: "docker://condaforge/mambaforge:22.11.1-4"



include: "rules/common.smk"
include: "rules/prep_merge_raw_data.smk"
# include: "rules/toblow5.smk"


##### target rules #####


rule all:
    input:
        'results/merged.bam',
        'results/merged.fastq.gz',
        'results/merged.blow5.idx',

