samples: config/samples.tsv



threads:
  samtools: 10

test_times: 3
depth:
  - 20
  - 30
  - 50
  - 100
  - 150

ratios:
  - 0.1
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 1