threads:
  samtools: 2
  slow5tools: 2
  f5c: 2
  select_blow5: 2

test_times: 3
depths:
  - 10
  - 20
  - 30

ratios:
  - 0.0
  - 0.1
  - 0.2
  - 0.3
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 1